# Generated by Django 3.1.3 on 2023-11-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Final', '0009_auto_20231120_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='openDate',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='openNumber',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='publicationNumber',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
