# Generated by Django 3.1.3 on 2023-11-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Final', '0012_auto_20231120_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='abstrCont',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='applicantName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='applicationDate',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='applicationNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='bigDrawing',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='drawing',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='inventionTitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='ipcNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='openDate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='openNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
