# Generated by Django 3.1.3 on 2023-11-27 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Final', '0013_auto_20231120_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='abstrCont',
            new_name='astrtCont',
        ),
    ]
