# Generated by Django 3.1.3 on 2023-12-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Final', '0014_auto_20231127_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='astrtCont',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
